# scons build file for cclient.so
# author vhg

env = Environment()
env.Append(CPPPATH = ['.','/daqfs/home/gurjyan/Work/include'])
env.Append(CCFLAGS = ['-g','-O3'])
env.Append(LIBPATH = ['/daqfs/home/gurjyan/Work/Linux-x86_64/lib'])
env.Append(LIBS = ['libcmsg', 'libcmsgRegex', 'libcmsgxx', 'librt', 'libpthread', 'libdl'])
env.SharedLibrary(source = 'cclient.c' )
