# scons build file for ACodaCC
# author vhg

env = Environment()
env.Append(CPPPATH = ['.','/daqfs/home/gurjyan/Work/include'])
env.Append(CCFLAGS = ['-g','-O3'])
env.Append(LIBPATH = ['/daqfs/home/gurjyan/Work/Linux-x86_64/lib'])
env.Append(LIBS = ['libcmsg', 'libcmsgRegex', 'libcmsgxx', 'librt', 'libpthread', 'libdl'])
env.Program(target = 'ACodaCC', source = 'accc.c' )
